// Action keys
script "FDTaunting" (void) NET {
	playSound (0, "*taunt", CHAN_VOICE);
}

script "FDKeys" ENTER {
	// Not needed or desired in TitleMaps.
	if (gameType () == Game_Title_Map)
		terminate;
	
	while (TRUE) {
		if (keyPressed (BT_RELOAD))
			useInventory ("FDReloadKey");
		
		delay (1);
	}
}
// Player move speed script made by DoomRater
script "PlayerSpeed" (int movespeed) {
	playerSpeed (movespeed);
}