// Misc user CVars
script "CVars" Enter {
	// Not needed or desired in TitleMaps.
	If (GameType () == Game_Title_Map)
		Terminate;
	while (true) {
		if (GetCVar ("FD_AutoReload")) GiveInventory ("EnableAutoReload", 1);
		else TakeInventory ("EnableAutoReload", 1);
		Delay (1);
	}
}

// Blood For The Blood God
script "FD_BloodForTheBloodGod" (void) {
	int result = GetCVar ("FD_BloodForTheBloodGod");
	SetResultValue (result);
}