// Thing_Deactivate
script "ThingDeactivate" (void) {
	Thing_Deactivate (ActivatorTID ());
}

// Meh
script "Water" Enter {
	// Not needed or desired in TitleMaps.
	If (GameType () == Game_Title_Map)
		Terminate;
	if (GetActorProperty(0,APROP_Waterlevel) > 2) // if underwater...
		GiveInventory ("IsUnderwater", 1); // give IsUnderwater
	else if (GetActorProperty(0,APROP_Waterlevel) <= 2) // if not underwater
		TakeInventory ("IsUnderwater", 1); // take IsUnderwater
		
	Delay (1);
	restart;
}

// Debug
script "Debug1" (int meh, int time) {
	int heh = meh;	
	int hue = heh * 2;
	while (TRUE) {
		if (heh == 0)
			terminate;
		hue = heh * 2;
		heh = hue;
		print (d:heh);	
		delay (time);
	}
}

script "Debug2" (int meh, int bla) {
	int heh = meh << bla;
	print (d:heh);
}

script "Debug3" (int meh,int bla) {
	int heh = meh >> bla;
	print (d:heh);
}

script "Debug4" (void) {
}

script "DKA" (void) {
	ACS_NamedTerminate ("Debug1", 0);
}

// Stuff
script "FD_CannotDropThisWeapon" (void) {
	HudMessage (s:"You cannot drop this weapon!";
				HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
}

int TriedToDropFistsOnce[MAXPLAYERS] = {0};
str FD_TryingToDropFistsMessages[7] = {
		"You're not Zharkov.",
		"Are you dumb?",
		"WHAT THE FUCK DO YOU WANT ME TO DO?!",
		"WAT.",
		"If you do that you will not be able to use anything, since your hands will not grow back.",
		"STAHP",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
		};
script "FD_TryingToDropFists" (void) {
	if (TriedToDropFistsOnce[PlayerNumber ()] == 0) {
		HudMessage (s:"You can't drop your fists!";
			HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
		TriedToDropFistsOnce[PlayerNumber ()] = 1;
	}
	
	else {
		int messageNumber = random (0, 6);
		HudMessage (s:FD_TryingToDropFistsMessages[messageNumber];
			HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
	}
}