// thing_Deactivate
script "ThingDeactivate" (void) {
	thing_Deactivate (activatorTID ());
}

// Meh
script "Water" ENTER {
	// Not needed or desired in TitleMaps.
	if (gameType () == Game_Title_Map)
		terminate;
	
	while (TRUE) {
		if (getActorProperty(0, APROP_WATERLEVEL) > 2) // if underwater...
			giveInventory ("IsUnderwater", 1); // give IsUnderwater

		else if (getActorProperty(0, APROP_WATERLEVEL) <= 2) // if not underwater
			takeInventory ("IsUnderwater", 1); // take IsUnderwater
			
		delay (1);
	}
}

// Debug
script "Debug1" (int meh, int time) {
	int heh = meh;	
	int hue = heh * 2;
	
	while (TRUE) {
		if (heh == 0)
			terminate;
		
		hue = heh * 2;
		heh = hue;
		print (d:heh);	
		delay (time);
	}
}

script "Debug2" (int meh, int bla) {
	int heh = meh << bla;
	
	print (d:heh);
}

script "Debug3" (int meh,int bla) {
	int heh = meh >> bla;
	
	print (d:heh);
}

script "DKA" (void) {
	ACS_NamedTerminate ("Debug1", 0);
}

// Stuff
script "FD_CannotDropThisWeapon" (void) {
	hudMessage (s:"You cannot drop this weapon!"; HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
}

int triedToDropFistsOnce [MAXPLAYERS] = {0};
#DEFINE FD_DropFstsMsgsCount 7
str FD_DropFstsMsgs [FD_DropFstsMsgsCount] = {
		"You're not Zharkov.",
		"Are you dumb?",
		"WHAT THE FUCK DO YOU WANT ME TO DO?!",
		"WAT.",
		"If you do that you will not be able to use anything, since your hands will not grow back.",
		"STAHP",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
};

script "FD_TryingToDropFists" (void) {
	if (triedToDropFistsOnce [playerNumber ()] == 0) {
		hudMessage (s:"You can't drop your fists!"; HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
		triedToDropFistsOnce [playerNumber ()] = 1;
	} else {
		int messageNumber = random (0, FD_DropFstsMsgsCount - 1);
		hudMessage (s:FD_DropFstsMsgs [messageNumber]; HUDMSG_FADEINOUT, 198198119, CR_UNTRANSLATED, 0.5, 0.6, 3.0, 0.3, 0.3);
	}
}