function int strcmp (int str1, int str2) {
    int i, j, k, l;
    int len1 = strLen (str1);
    int len2 = strLen (str2);
    j = max (len1, len2);
 
    for (i = 0; i < j; i++) {
        if (i >= len1)
			return -1;
		
        if (i >= len2)
			return 1;
		
        k = getChar (str1, i);
		l = getChar (str2, i);
		
        if (k > j)
			return 1;
		
        if (k < j)
			return -1;
    }
	
    return 0;
}